name: User-Story
description: Create a user story 
title: "[User Story]: "
labels: ["user-story"]
projects: ["ipa/IPA-2025"]
assignees:
  - Vakmeth
body:
  - type: textarea
    id: request
    attributes:
      label: What should be implemented?
      placeholder: As a XXX I want to XXX because XXX
    validations:
      required: true
  - type: dropdown
    id: sprint
    attributes:
      label: sprint
      description: What sprint should this task be completed in?
      options:
        - 'Sprint 1: Initialisation'
        - 'Sprint 2: Implementation'
        - 'Sprint 3: Finalization'
      default: 0
    validations:
      required: true
  - type: input
    id: effort
    attributes:
      label: Effort in man-hours
      description: How many man-hours will this user-story take?
    validations:
      required: true
